server:
  port: 9032
spring:
  application:
    name: abc
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    cluster:
      nodes:
        - localhost:6380
        - localhost:6381
        - localhost:6381

