spring:
  cloud:
    zookeeper:
      connect-string: localhost:2181
  application:
    name: demo-servlet-zk


server:
  port: 9123
logging:
  level:
    com.github.huifer: debug



fast:
  view:
    password: 1
    username: 1
    zk:
      url-mapping: /ac/*