server:
  port: 8132
  servlet:
    context-path: /bac
logging:
  level:
    com.github.huifer: debug


spring:
  redis:
    database: 1
    port: 6379
    host: 127.0.0.1
fast:
  view:
    username: 1
    password: 1
    redis:
      url-mapping: /ac/*